'use strict';
// Replace this sample-data factory when a backend is introduced. No credentials live here.
HC.createDemoData = function () {
  const types = [
    {
      id: 'T001',
      name: 'Standard',
      price: 150,
      capacity: 2,
      beds: '1 queen bed',
      description: 'A cozy retreat with thoughtful comforts and a quiet garden outlook.',
    },
    {
      id: 'T002',
      name: 'Deluxe',
      price: 220,
      capacity: 2,
      beds: '1 king bed',
      description: 'Wake up slowly in a light-filled room with space to unwind.',
    },
    {
      id: 'T003',
      name: 'Suite',
      price: 260,
      capacity: 3,
      beds: '1 king + sofa bed',
      description: 'A generous hideaway with a lounge and warm, inviting details.',
    },
    {
      id: 'T004',
      name: 'Private Villa',
      price: 480,
      capacity: 6,
      beds: '2 king + sofa bed',
      description: 'Your own poolside escape, made for long days and unforgettable stays.',
    },
  ];
  const rooms = [
    {
      id: 1,
      number: '201',
      floor: 2,
      type: 'Deluxe',
      name: 'Ocean View Room',
      status: 'Available',
      image: 'assets/images/rooms/ocean.jpg',
      amenities: ['Wi-Fi', 'Ocean outlook'],
    },
    {
      id: 2,
      number: '301',
      floor: 3,
      type: 'Suite',
      name: 'Deluxe Room',
      status: 'Available',
      image: 'assets/images/rooms/deluxe.jpg',
      amenities: ['Wi-Fi', 'Lounge area'],
    },
    {
      id: 3,
      number: 'V01',
      floor: 0,
      type: 'Private Villa',
      name: 'Private Pool Villa',
      status: 'Available',
      image: 'assets/images/rooms/villa.jpg',
      amenities: ['Private pool', 'Terrace'],
    },
    {
      id: 4,
      number: '101',
      floor: 1,
      type: 'Standard',
      name: 'Garden Room',
      status: 'Available',
      image: 'assets/images/rooms/deluxe.jpg',
      amenities: ['Wi-Fi', 'Garden view'],
    },
    {
      id: 5,
      number: '202',
      floor: 2,
      type: 'Deluxe',
      name: 'Coastal Deluxe',
      status: 'Reserved',
      image: 'assets/images/rooms/ocean.jpg',
      amenities: ['Wi-Fi', 'Balcony'],
    },
    {
      id: 6,
      number: '302',
      floor: 3,
      type: 'Suite',
      name: 'Sunset Suite',
      status: 'Occupied',
      image: 'assets/images/rooms/deluxe.jpg',
      amenities: ['Wi-Fi', 'Lounge area'],
    },
    {
      id: 7,
      number: '102',
      floor: 1,
      type: 'Standard',
      name: 'Courtyard Room',
      status: 'Maintenance',
      image: 'assets/images/rooms/deluxe.jpg',
      amenities: ['Wi-Fi', 'Courtyard'],
    },
    {
      id: 8,
      number: 'V02',
      floor: 0,
      type: 'Private Villa',
      name: 'Palm Pool Villa',
      status: 'Available',
      image: 'assets/images/rooms/villa.jpg',
      amenities: ['Private pool', 'Terrace'],
    },
    {
      id: 9,
      number: '203',
      floor: 2,
      type: 'Deluxe',
      name: 'Pacific Room',
      status: 'Occupied',
      image: 'assets/images/rooms/ocean.jpg',
      amenities: ['Wi-Fi', 'Balcony'],
    },
  ].map((room) => {
    const type = types.find((t) => t.name === room.type);
    return {
      ...room,
      price: type.price,
      capacity: type.capacity,
      beds: type.beds,
      description: type.description,
    };
  });
  const customers = [
    {
      id: 'C001',
      name: 'Alex Morgan',
      email: 'alex@example.com',
      phone: '+1 202-555-0101',
      status: 'Active',
    },
    {
      id: 'C002',
      name: 'Sofia Chen',
      email: 'sofia@example.com',
      phone: '+1 202-555-0102',
      status: 'Active',
    },
    {
      id: 'C003',
      name: 'Noah Williams',
      email: 'noah@example.com',
      phone: '+1 202-555-0103',
      status: 'Active',
    },
    {
      id: 'C004',
      name: 'Amelia Patel',
      email: 'amelia@example.com',
      phone: '+1 202-555-0104',
      status: 'Active',
    },
    {
      id: 'C005',
      name: 'Oliver Davis',
      email: 'oliver@example.com',
      phone: '+1 202-555-0105',
      status: 'Inactive',
    },
  ];
  const reservations = [
    {
      id: 'HC-1001',
      customerId: 'C001',
      roomId: 1,
      checkIn: HC.today(7),
      checkOut: HC.today(10),
      guests: 2,
      status: 'Confirmed',
      paymentStatus: 'Pending',
    },
    {
      id: 'HC-1002',
      customerId: 'C001',
      roomId: 2,
      checkIn: HC.today(-15),
      checkOut: HC.today(-12),
      guests: 2,
      status: 'Completed',
      paymentStatus: 'Paid',
    },
    {
      id: 'HC-1003',
      customerId: 'C002',
      roomId: 5,
      checkIn: HC.today(),
      checkOut: HC.today(3),
      guests: 2,
      status: 'Confirmed',
      paymentStatus: 'Paid',
    },
    {
      id: 'HC-1004',
      customerId: 'C003',
      roomId: 6,
      checkIn: HC.today(-3),
      checkOut: HC.today(),
      guests: 3,
      status: 'Checked In',
      paymentStatus: 'Paid',
    },
    {
      id: 'HC-1005',
      customerId: 'C001',
      roomId: 3,
      checkIn: HC.today(-7),
      checkOut: HC.today(-5),
      guests: 4,
      status: 'Cancelled',
      paymentStatus: 'Refunded',
    },
    {
      id: 'HC-1006',
      customerId: 'C001',
      roomId: 4,
      checkIn: HC.today(14),
      checkOut: HC.today(16),
      guests: 1,
      status: 'Pending',
      paymentStatus: 'Failed',
    },
    {
      id: 'HC-1007',
      customerId: 'C004',
      roomId: 9,
      checkIn: HC.today(-2),
      checkOut: HC.today(1),
      guests: 2,
      status: 'Checked In',
      paymentStatus: 'Pending',
    },
  ].map((r) => {
    const room = rooms.find((item) => item.id === r.roomId);
    return {
      ...r,
      guest: customers.find((c) => c.id === r.customerId).name,
      roomName: room.name,
      roomType: room.type,
      roomNumber: room.number,
      nightlyRate: room.price,
      total: HC.nights(r.checkIn, r.checkOut) * room.price,
      requests: '',
    };
  });
  const payments = reservations.map((r, i) => ({
    id: `PAY-${2001 + i}`,
    reservationId: r.id,
    customerId: r.customerId,
    customer: r.guest,
    amount: r.total,
    method: i % 2 ? 'Card' : 'Pay at Hotel',
    status: r.paymentStatus,
    date: HC.today(),
  }));
  const staff = [
    {
      id: 'S001',
      name: 'Jamie Rivera',
      role: 'Receptionist',
      email: 'jamie@example.com',
      phone: '+1 202-555-0121',
      status: 'Active',
    },
    {
      id: 'S002',
      name: 'Taylor Brooks',
      role: 'Admin',
      email: 'taylor@example.com',
      phone: '+1 202-555-0122',
      status: 'Active',
    },
    {
      id: 'S003',
      name: 'Jordan Lee',
      role: 'Manager',
      email: 'jordan@example.com',
      phone: '+1 202-555-0123',
      status: 'Active',
    },
    {
      id: 'S004',
      name: 'Riley Kim',
      role: 'Receptionist',
      email: 'riley@example.com',
      phone: '+1 202-555-0124',
      status: 'Inactive',
    },
  ];
  return {
    version: 1,
    seedDate: HC.today(),
    rooms,
    types,
    customers,
    reservations,
    payments,
    staff,
    activity: [
      {
        actor: 'Jamie Rivera',
        message: 'reviewed today’s expected arrivals.',
        time: 'Today · 08:15',
      },
      { actor: 'Jordan Lee', message: 'marked room 102 for maintenance.', time: 'Today · 08:30' },
      {
        actor: 'Taylor Brooks',
        message: 'reviewed room rates for the coming week.',
        time: 'Today · 09:00',
      },
    ],
  };
};
